language: python

python:
  - "3.6"

before_install:
    - python --version
    - docker build -t seflask
    - pip install -U pip
    - pip install -U pytest

install:
    - pip install flask
    - pip install -r requirements.txt

script:
    - docker run -d -p 127.0.0.1:5000:5000 seflask sh -c "python app.py && flake8"
    #- pytest